export const initialallTemplatedata = [
    {
        id: 1002,
        instanceId: 1,
        doc: '1',
        briefName: 'new',
        graphRenderData: {
            nodes: [
                {
                    id: '94a8b140-7671-4edb-8bbb-052969e88c02',
                    type: 'task',
                    height: 320,
                    width: 400,
                    x: 100,
                    y: 100,
                    properties: {
                        id: '1',
                        instanceId: '1',
                        outputhandlArg: {
                            label: 'opop',
                            name: 'opop',
                            type: 'string',
                            doc: '',
                            uiComponent: 'select',
                            isFixedValue: false,
                            allowEdit: true,
                        },
                        inputhandlArg: [
                            {
                                label: 'jj',
                                name: 'jj',
                                type: 'string',
                                doc: '',
                                uiComponent: 'select',
                                isFixedValue: false,
                                allowEdit: true,
                            },
                            {
                                type: 'undefined',
                                doc: '',
                                uiComponent: 'AutoComplete',
                                value: 'jj',
                                isFixedValue: true,
                                allowEdit: true,
                            },
                        ],
                        inputArgs: [
                            {
                                label: 'jj',
                                name: 'jj',
                                type: 'string',
                            },
                        ],
                        outputArgs: [
                            {
                                label: 'opop',
                                name: 'opop',
                                type: 'string',
                                doc: '',
                            },
                        ],
                        handle: 'add',
                        handleType: 'basicTask',
                        inputTask: [],
                        outputTask: [],
                    },
                },
                {
                    id: '3bf1e86c-3cc5-4bb1-a3cb-ca855d4958f2',
                    type: 'task',
                    height: 320,
                    width: 400,
                    x: 480,
                    y: 660,
                    properties: {
                        id: '14',
                        instanceId: '1',
                        outputhandlArg: {
                            label: 'hh',
                            name: 'hh',
                            type: 'string',
                            doc: '',
                            uiComponent: 'select',
                            isFixedValue: false,
                            allowEdit: true,
                        },
                        inputhandlArg: [
                            [
                                {
                                    label: 's',
                                    name: 's',
                                    type: 'string',
                                    doc: '',
                                    uiComponent: 'selectmultiple',
                                    isFixedValue: false,
                                    allowEdit: true,
                                },
                                {
                                    label: 'zz',
                                    name: 'zz',
                                    type: 'string',
                                    doc: '',
                                    uiComponent: 'selectmultiple',
                                    isFixedValue: false,
                                    allowEdit: true,
                                },
                            ],
                        ],
                        inputArgs: [
                            {
                                label: 's',
                                name: 's',
                                type: 'string',
                            },
                            {
                                label: 'zz',
                                name: 'zz',
                                type: 'string',
                            },
                        ],
                        outputArgs: [
                            {
                                label: 'hh',
                                name: 'hh',
                                type: 'string',
                                doc: '',
                            },
                        ],
                        handle: 'sum',
                        handleType: 'basicTask',
                        inputTask: [],
                        outputTask: [],
                    },
                },
                {
                    id: 'b17950ad-c69e-419e-b00a-bdd1f61c930a',
                    type: 'task',
                    height: 320,
                    width: 400,
                    x: -60,
                    y: 640,
                    properties: {
                        id: '2',
                        instanceId: '1',
                        outputhandlArg: {
                            label: 'hh',
                            name: 'hh',
                            type: 'string',
                            doc: '',
                            uiComponent: 'select',
                            isFixedValue: false,
                            allowEdit: true,
                        },
                        inputhandlArg: [
                            {
                                label: 'jj',
                                name: 'jj',
                                type: 'string',
                                doc: '',
                                uiComponent: 'select',
                                isFixedValue: false,
                                allowEdit: true,
                            },
                            {
                                type: 'undefined',
                                doc: '',
                                uiComponent: 'AutoComplete',
                                value: 'jj',
                                isFixedValue: true,
                                allowEdit: true,
                            },
                        ],
                        inputArgs: [
                            {
                                label: 'jj',
                                name: 'jj',
                                type: 'string',
                            },
                        ],
                        outputArgs: [
                            {
                                label: 'hh',
                                name: 'hh',
                                type: 'string',
                                doc: '',
                            },
                        ],
                        handle: 'sub',
                        handleType: 'basicTask',
                        inputTask: [],
                        outputTask: [],
                    },
                },
            ],
            edges: [
                {
                    id: '6cfc6b3e-d0fa-4f12-9eee-bf8a3553369b',
                    type: 'polyline',
                    sourceNodeId: '94a8b140-7671-4edb-8bbb-052969e88c02',
                    targetNodeId: 'b17950ad-c69e-419e-b00a-bdd1f61c930a',
                },
                {
                    id: 'a6d81772-874d-4f92-b963-11d04ec09f20',
                    type: 'polyline',
                    sourceNodeId: '94a8b140-7671-4edb-8bbb-052969e88c02',
                    targetNodeId: '3bf1e86c-3cc5-4bb1-a3cb-ca855d4958f2',
                },
            ],
        },
        componentArg: null,
        handleType: 'template',
        handle: ['1_1'],
        memoChildren: ['1_1', '14_1', '2_1'],
        inputTask: {},
        outputTask: {},
    },
];
export const tempGraphrenderData = {
    edges: [
        {
            type: 'polyline',
            sourceNodeId: 'rect_2',
            targetNodeId: 'control_1',
        },
        {
            type: 'polyline',
            sourceNodeId: 'rect_3',
            targetNodeId: 'control_1',
        },
        {
            type: 'polyline',
            sourceNodeId: 'control_1',
            targetNodeId: 'rect_4',
        },
    ],
    nodes: [
        {
            id: 'rect_2',
            type: 'task',
            height: 320,
            width: 400,
            x: 380,
            y: 340,
            properties: {
                id: '1',
                instanceId: '1',
                outputhandlArg: {
                    label: 'opop',
                    name: 'opop',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 'jj',
                        name: 'jj',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 'jj',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 'jj',
                        name: 'jj',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'opop',
                        name: 'opop',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'add',
                handleType: 'basicTask',
            },
        },
        {
            id: 'rect_3',
            type: 'task',
            height: 320,
            width: 400,
            x: 880,
            y: 340,
            properties: {
                id: '1',
                instanceId: '2',
                outputhandlArg: {
                    label: 'opopio',
                    name: 'opopio',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 's',
                        name: 's',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 's',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 's',
                        name: 's',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'opopio',
                        name: 'opopio',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'add',
                handleType: 'basicTask',
            },
        },
        {
            id: 'rect_4',
            type: 'task',
            height: 320,
            width: 400,
            x: 680,
            y: 1040,
            properties: {
                id: '4',
                instanceId: '1',
                outputhandlArg: {
                    label: 'y',
                    name: 'y',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 'rt',
                        name: 'rt',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 'rt',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 'rt',
                        name: 'rt',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'y',
                        name: 'y',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'divide',
                handleType: 'basicTask',
            },
        },
        {
            id: 'control_1',
            type: 'processControlWaitAll',
            height: 80,
            width: 100,
            x: 680,
            y: 720,
            properties: {
                id: 100,
                instanceId: '1',
                handleType: 'processControl',
                handle: 'processControlWaitAll',
            },
        },
    ],
};
