export const initialallTemplatedata = [
    {
        id: 1000,
        instanceId: 1,
        doc: '1',
        briefName: 'start',
        componentArg: null,
        handleType: 'templateGroup',
        handle: ['1_1', '3_1'],
        memoChildren: ['1_1', '3_1', '14_1'],
        inputTask: {},
        outputTask: {},
        gen:false,
    },
];
export const initialRes = {
    '1_1': {
        gen:false,
        id: '1',
        instanceId: '1',
        outputhandlArg: {
            label: 'opop',
            name: 'opop',
            type: 'string',
            doc: '',
            uiComponent: 'select',
            isFixedValue: false,
            allowEdit: true,
        },
        inputhandlArg: [
            {
                label: 'jj',
                name: 'jj',
                type: 'string',
                doc: '',
                uiComponent: 'select',
                isFixedValue: false,
                allowEdit: true,
            },
            {
                label: '2',
                name: '2',
                type: 'string',
                doc: '',
                uiComponent: 'AutoComplete',
                isFixedValue: false,
                allowEdit: true,
            },
        ],
        inputArgs: [
            {
                label: 'jj',
                name: 'jj',
                type: 'string',
            },
        ],
        outputArgs: [
            {
                label: 'opop',
                name: 'opop',
                type: 'string',
                doc: '',
            },
        ],
        handle: 'add',
        handleType: 'task',
        inputTask: [],
        outputTask: ['14_1'],
        parId:'1000_1'
    },
    '14_1': {
        nodeSize: {
            width: 417,
            height: 355,
        },
        parId:'1000_1',
        id: '14',
        instanceId: '1',
        outputhandlArg: {
            label: 'end',
            name: 'end',
            type: 'string',
            doc: '',
            uiComponent: 'select',
            isFixedValue: false,
            allowEdit: true,
        },
        inputhandlArg: [
            [
                {
                    label: 'res',
                    name: 'res',
                    type: 'string',
                    doc: '',
                    uiComponent: 'selectmultiple',
                    isFixedValue: false,
                    allowEdit: true,
                },
                {
                    label: 'opop',
                    name: 'opop',
                    type: 'string',
                    doc: '',
                    uiComponent: 'selectmultiple',
                    isFixedValue: false,
                    allowEdit: true,
                },
            ],
        ],
        inputArgs: [
            {
                label: 'res',
                name: 'res',
                type: 'string',
            },
            {
                label: 'opop',
                name: 'opop',
                type: 'string',
            },
        ],
        outputArgs: [
            {
                label: 'end',
                name: 'end',
                type: 'string',
                doc: '',
            },
        ],
        handle: 'sum',
        handleType: 'task',
        inputTask: ['1_1', '3_1'],
        outputTask: [],
        parId: '1000_1',
        gen:false,
    },
    '3_1': {
        parId:'1000_1',
        id: '3',
        instanceId: '1',
        gen:false,
        outputhandlArg: {
            label: 'res',
            name: 'res',
            type: 'string',
            doc: '',
            uiComponent: 'select',
            isFixedValue: false,
            allowEdit: true,
        },
        inputhandlArg: [
            {
                label: 'rt',
                name: 'rt',
                type: 'string',
                doc: '',
                uiComponent: 'select',
                isFixedValue: false,
                allowEdit: true,
            },
            {
                label: '4',
                name: '4',
                type: 'string',
                doc: '',
                uiComponent: 'AutoComplete',
                isFixedValue: false,
                allowEdit: true,
            },
        ],
        inputArgs: [
            {
                label: 'rt',
                name: 'rt',
                type: 'string',
            },
        ],
        outputArgs: [
            {
                label: 'res',
                name: 'res',
                type: 'string',
                doc: '',
            },
        ],
        handle: 'multipy',
        handleType: 'task',
        inputTask: [],
        outputTask: ['14_1'],
    },
    '1000_1': {
        gen:false,
        id: 1000,
        instanceId: 1,
        doc: '1',
        briefName: 'start',
        componentArg: null,
        handleType: 'templateGroup',
        handle: ['1_1', '3_1'],
        memoChildren: ['1_1', '3_1', '14_1'],
        inputTask: {},
        outputTask: {},
    },
};
export const tempGraphrenderData = {
    edges: [
        {
            type: 'polyline',
            sourceNodeId: 'rect_2',
            targetNodeId: 'control_1',
        },
        {
            type: 'polyline',
            sourceNodeId: 'rect_3',
            targetNodeId: 'control_1',
        },
        {
            type: 'polyline',
            sourceNodeId: 'control_1',
            targetNodeId: 'rect_4',
        },
    ],
    nodes: [
        {
            id: 'rect_2',
            type: 'task',
            height: 320,
            width: 400,
            x: 380,
            y: 340,
            properties: {
                id: '1',
                instanceId: '1',
                outputhandlArg: {
                    label: 'opop',
                    name: 'opop',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 'jj',
                        name: 'jj',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 'jj',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 'jj',
                        name: 'jj',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'opop',
                        name: 'opop',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'add',
                handleType: 'task',
            },
        },
        {
            id: 'rect_3',
            type: 'task',
            height: 320,
            width: 400,
            x: 880,
            y: 340,
            properties: {
                id: '1',
                instanceId: '2',
                outputhandlArg: {
                    label: 'opopio',
                    name: 'opopio',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 's',
                        name: 's',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 's',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 's',
                        name: 's',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'opopio',
                        name: 'opopio',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'add',
                handleType: 'task',
            },
        },
        {
            id: 'rect_4',
            type: 'task',
            height: 320,
            width: 400,
            x: 680,
            y: 1040,
            properties: {
                id: '4',
                instanceId: '1',
                outputhandlArg: {
                    label: 'y',
                    name: 'y',
                    type: 'string',
                    doc: '',
                    uiComponent: 'select',
                    isFixedValue: false,
                    allowEdit: true,
                },
                inputhandlArg: [
                    {
                        label: 'rt',
                        name: 'rt',
                        type: 'string',
                        doc: '',
                        uiComponent: 'select',
                        isFixedValue: false,
                        allowEdit: true,
                    },
                    {
                        type: 'undefined',
                        doc: '',
                        uiComponent: 'AutoComplete',
                        value: 'rt',
                        isFixedValue: true,
                        allowEdit: true,
                    },
                ],
                inputArgs: [
                    {
                        label: 'rt',
                        name: 'rt',
                        type: 'string',
                    },
                ],
                outputArgs: [
                    {
                        label: 'y',
                        name: 'y',
                        type: 'string',
                        doc: '',
                    },
                ],
                handle: 'divide',
                handleType: 'task',
            },
        },
        {
            id: 'control_1',
            type: 'processControlWaitAll',
            height: 80,
            width: 100,
            x: 680,
            y: 720,
            properties: {
                id: 100,
                instanceId: '1',
                handleType: 'processControl',
                handle: 'processControlWaitAll',
            },
        },
    ],
};
